site_name: Molecular Dynamics

theme:
  name: material
  custom_dir: material
  palette:
    primary: blue
  logo: overrides/assets/logo.svg
  favicon: overrides/assets/images/favicon.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

site_author: David G Oppenheimer
site_description: >-
  Notes for running and analyzing molecular dynamics simulations

# Copyright
copyright: Copyright &copy; 2022 David G Oppenheimer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

