#================================================================#
# Site Information
#================================================================#

site_name: Molecular Dynamics
site_author: David G Oppenheimer
site_description: >-
  My notes for preparing, running, and analyzing molecular dynamics simulations using Google Colab and Jupyter notebooks
repo_name: "dgoppenheimer/mk-test4"
repo_url: https://github.com/dgoppenheimer/mk-test4
site_url: https://dgoppenheimer.github.io/mk-test4/
copyright: Copyright &copy; 2022 David G Oppenheimer

#================================================================#
# Mkdocs Theme (Material Mkdocs) + Extras
#================================================================#

theme:
  name: material
  custom_dir: material
  palette:
    primary: blue
  logo: overrides/assets/logo.svg
  favicon: overrides/assets/images/favicon.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

#================================================================#
# Mkdocs Markdown Extensions, Plugins & extras
#================================================================#

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true

plugins:
    - mkdocs-video

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#================================================================#
# Mkdocs Navigation Tree
#================================================================#

nav:
  - Home: ./index.md
  - User Guide:
    - Introduction: user-guide/introduction.md
    - Getting Started: user-guide/getting-started.md
    - Building This Site: user-guide/building-this-site.md
