site_name: Molecular Dynamics
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/images/favicon.png
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

